package chess.game;

public enum GameMode {
    CLASSIC,
    FISCHER_RANDOM,
    DISPLACED,
    TRANSCENDENTAL,
    RETIRED,
    CONSTRUCTOR,
    EXTINCTION,
    THREE_CHECKS,
    JEDI,
    PROGRESSIVE,
    MONSTER,
    BATTLE_KINGS,
    BERLIN,
    CAPABLANCA,
    RANDOM_CAPABLANCA,
    GRAND,
    PRACTICE
}
